### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by Xiar-fatah** [Xiar-fatah/boopy#20]
Create requirements.txt that contains all the packages that boopy uses to make it easier for new users to start using the package.

**Comment by anshikjain18** [comment]
Hello @Xiar-fatah, I am interested in working on this issue. This will be the first issue I will contribute to, so I would greatly appreciate any tips, context, and guidelines.

**Comment by Xiar-fatah** [comment]
Great! I accidentally started on this issue. However, there is still the following modules that are missing in the requirements.txt
```
sphinx
sphinx-automodapi
jupyter-sphinx
```
I would be glad if you could add them and their specific version that is compatible with this project.

**Comment by Xiar-fatah** [comment]
Fixed in 4d51478
